"Generated by paket2bazel"

load("@rules_dotnet//dotnet:defs.bzl", "nuget_repo")

def Main():
    "Main"
    nuget_repo(
        name = "main",
        packages = [
            ("Microsoft.NETCore.Platforms", "7.0.1", "sha512-Hid6GWJiAHktqd180NbVOUaruWTqaeOxnMH7JbueuaLy0RIs334TZDAf0rOeNmzpiPMabmaeJchUfLPlD0kv1w==", [], []),
            ("Microsoft.NETCore.Targets", "5.0.0", "sha512-hYHm3JAjQO/nySxcl1EpZhYEW+2P3H1eLZNr+QxgO5TnLS6hqtfi5WchjQzjid45MYmhy2X7IOmcWtDP4fpMGw==", [], []),
            ("System.Runtime", "4.3.1", "sha512-Al69mPDfzdD+bKGK2HAfB+lNFOHFqnkqzNnUJmmvUe1/qEPK9M7EiTT4zuycKDPy7ev11xz8XVgJWKP0hm7NIA==", ["Microsoft.NETCore.Platforms", "Microsoft.NETCore.Targets"], []),
        ],
    )
